<?php
/*
UploadiFive
Copyright (c) 2012 Reactive Apps, Ronnie Garcia
*/

/*
IMPORTANT: This script requires the PHP GD library
*/

// Set the uplaod directory
$uploadDir = __DIR__ . '/../../images/upload/' . substr($_POST['timestamp'], 0, 4) . '/';
if(!is_dir($uploadDir)){
    mkdir($uploadDir);
    chmod($uploadDir, 0777);
}

function errorHandler($errno, $errstr, $errfile, $errline) {
	// In this script, the silently suppress any error generated by getimagesize
	// which will throw an error if the "image" isn't an image
	// ie doesn't have a valid width / height

    /* Don't execute PHP internal error handler */
    return true;
}

$old_error_handler = set_error_handler("errorHandler");

// Check if the file has a width and height
function isImage($tempFile) {

	// Get the size of the image
    $size = getimagesize($tempFile);

	if (isset($size) && $size[0] && $size[1] && $size[0] *  $size[1] > 0) {
		return true;
	} else {
		return false;
	}

}

if (!empty($_FILES)) {

	$fileData = $_FILES['Filedata'];

        include_once __DIR__ . '/../../vendor/nette/utils/src/Utils/Strings.php';
        
	if ($fileData) {
		$tempFile   = $fileData['tmp_name'];
                $fileName = explode('.', $fileData['name']);
                $postFix = $fileName[count($fileName) - 1];
                unset ($fileName[count($fileName) - 1]);

                $fileName = $_POST['timestamp'] . '_' . Nette\Utils\Strings::webalize(implode('.', $fileName)) . '.' . $postFix;
		$targetFile = $uploadDir . $fileName;

		// Validate the file type
		$fileTypes = array('jpg', 'jpeg', 'gif', 'png'); // Allowed file extensions
		$fileParts = pathinfo($fileData['name']);

		// Validate the filetype
		if (in_array(strtolower($fileParts['extension']), $fileTypes) && filesize($tempFile) > 0 && isImage($tempFile)) {
			// Save the file
			if(move_uploaded_file($tempFile, $targetFile) !== TRUE){
                            echo 'ERROR';
                        }else{
                            //echo $targetFile;
                            echo $fileName;
                        }
			
		} else {

			// The file type wasn't allowed
			echo 'Invalid file type.';
		}
	}
}
?>